spring.application.name=api_usuarios


# Puerto de la api
server.port=8080

#Configuracion de conexion a la bda
sping.datasource.url=jdbc:mysql://localhost:3306/usuarios_bda
spring.datasource.usarname=root
spring.datasource.password=root


#driver JBCD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Confirugacion JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true